apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Manifest
metadata:
  name: sample
spec:
  arches:
    - arm64
    - amd64
  operatingSystems:
    - arch: amd64
      type: linux
      id: uos
      version: "20"
      osImage: UOS Server 20
      repository:
        iso:
          localPath: /root/uos/rpms/uos20-amd64-rpms.iso
    - arch: arm64
      type: linux
      id: uos
      version: "20"
      osImage: UOS Server 20
      repository:
        iso:
          localPath: /root/uos/rpms/uos20-arm64-rpms.iso
    - arch: amd64
      type: linux
      id: kylin
      version: "v10sp3"
      osImage: kylin v10 sp3
      repository:
        iso:
          localPath: /root/uos/rpms/kylinv10sp3-amd64-rpms.iso
    - arch: arm64
      type: linux
      id: kylin
      version: "v10sp3"
      osImage: kylin v10 sp3
      repository:
        iso:
          localPath: /root/uos/rpms/kylinv10sp3-arm64-rpms.iso
    - arch: amd64
      type: linux
      id: centos
      version: "7"
      osImage: centos7
      repository:
        iso:
          localPath: /root/uos/rpms/centos7-rpms-amd64.iso
    - arch: arm64
      type: linux
      id: centos
      version: "7"
      osImage: centos7
      repository:
        iso:
          localPath: /root/uos/rpms/centos7-rpms-arm64.iso
    - arch: amd64
      type: linux
      id: ubuntu
      version: "22.04"
      osImage: ubuntu 22.04
      repository:
        iso:
          localPath: /root/uos/rpms/ubuntu-22.04-debs-amd64.iso
    - arch: arm64
      type: linux
      id: ubuntu
      version: "22.04"
      osImage: ubuntu 22.04
      repository:
        iso:
          localPath: /root/uos/rpms/ubuntu-22.04-debs-arm64.iso
  kubernetesDistributions:
    - type: kubernetes
      version: v1.32.0
  components:
    helm:
      version: v3.14.3
    cni:
      version: v1.2.0
    etcd:
      version: v3.5.13
    containerRuntimes:
      - type: docker
        version: 24.0.9
      - type: containerd
        version: 1.7.13
    calicoctl:
      version: v3.27.4
    crictl:
      version: v1.29.0
    docker-registry:
      version: "2"
    harbor:
      version: v2.10.1
    docker-compose:
      version: v2.26.1
  images:
    - docker.io/kubesphere/pause:3.9
    - docker.io/kubesphere/kube-apiserver:v1.28.15
    - docker.io/kubesphere/kube-controller-manager:v1.28.15
    - docker.io/kubesphere/kube-scheduler:v1.28.15
    - docker.io/kubesphere/kube-proxy:v1.28.15
    - docker.io/coredns/coredns:1.9.3
    - docker.io/kubesphere/k8s-dns-node-cache:1.22.20
    - docker.io/calico/kube-controllers:v3.27.4
    - docker.io/calico/cni:v3.27.4
    - docker.io/calico/node:v3.27.4
    - docker.io/calico/pod2daemon-flexvol:v3.27.4
    - docker.io/calico/typha:v3.27.4
    - docker.io/flannel/flannel:v0.21.3
    - docker.io/flannel/flannel-cni-plugin:v1.1.2
    - docker.io/cilium/cilium:v1.15.3
    - docker.io/cilium/operator-generic:v1.15.3
    - docker.io/hybridnetdev/hybridnet:v0.8.6
    - docker.io/kubeovn/kube-ovn:v1.10.10
    - docker.io/kubesphere/multus-cni:v3.8
    - docker.io/openebs/provisioner-localpv:3.3.0
    - docker.io/openebs/linux-utils:3.3.0
    - docker.io/library/haproxy:2.9.6-alpine
    - docker.io/plndr/kube-vip:v0.7.2
    - docker.io/kubesphere/kata-deploy:stable
    - docker.io/kubesphere/node-feature-discovery:v0.10.0
  registry:
    auths: {}
